# Generated by Django 5.0.2 on 2024-03-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ferramentas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=20, null=True)),
                ('grupo', models.CharField(max_length=20, null=True)),
                ('montadora', models.CharField(max_length=50, null=True)),
                ('aplicacao', models.CharField(max_length=50, null=True)),
                ('quantidade', models.CharField(max_length=20)),
                ('observacoes', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
