# Generated by Django 5.0.2 on 2024-05-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='faltantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('peca', models.TextField(max_length=100)),
                ('cor', models.TextField(max_length=20, null=True)),
                ('qtd', models.IntegerField(verbose_name=1000)),
            ],
        ),
        migrations.CreateModel(
            name='pedidosfaltantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numerodopedido', models.TextField()),
                ('dataLancamento', models.DateField()),
                ('pecas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faltantes')),
            ],
            options={
                'db_table': 'pedidosfaltantes',
            },
        ),
    ]
