# Generated by Django 5.0.2 on 2024-05-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faltantes_pedidosfaltantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidosfaltantes',
            name='pecas',
        ),
        migrations.AddField(
            model_name='pedidosfaltantes',
            name='pecas',
            field=models.ManyToManyField(to='core.faltantes'),
        ),
    ]
