# Generated by Django 5.0.2 on 2024-05-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pedidosfaltantes_pecas_pedidosfaltantes_pecas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDeSeparacao',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('observacoes', models.CharField(max_length=255, null=True)),
                ('dataRecebimento', models.DateField()),
                ('dataEntrega', models.DateField(null=True)),
            ],
            options={
                'db_table': 'PedidoDeSeparacao',
            },
        ),
        migrations.RemoveField(
            model_name='pedidosfaltantes',
            name='pecas',
        ),
        migrations.AlterField(
            model_name='faltantes',
            name='qtd',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('peca', models.TextField(max_length=100)),
                ('cor', models.TextField(max_length=20, null=True)),
                ('qtd', models.IntegerField()),
                ('pedido', models.ManyToManyField(to='core.pedidodeseparacao')),
            ],
            options={
                'db_table': 'produtos',
            },
        ),
    ]
